# Nod — developer entry points.
#
# `make check` is the gate (CLAUDE.md §5): ruff, mypy, pytest with the coverage
# gate, and a bench smoke test. Run it before declaring anything done.

SHELL := bash
# NOTE: inert on GNU make 3.81, which is what macOS ships (2006, and still the
# stock /usr/bin/make). `.SHELLFLAGS` arrived in 3.82, so on a Mac this line is
# read and ignored: `false | true` succeeds and the recipe continues. Verified
# directly, not assumed. It is kept because it is correct on 3.82+, but **do not
# rely on it** — any recipe that needs a pipeline's failure to propagate must
# say so itself, as `gate` does below. A guard that has never once fired is the
# CLAUDE.md §5 defect in the build file rather than the test suite.
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := help

UV := uv
RUN := $(UV) run

# soundfile, librosa and scipy live in the `bench` extra (CLAUDE.md §3: audio is
# bench-only, and DEPLOYMENT §3 keeps it out of the runtime image). A bare
# `uv run` installs the base dependencies only, so any target importing
# nod_bench.corpus, .perturb or .replay must ask for the extra explicitly.
# Found by cloning the pushed branch and running `make bench` in it, which
# failed on `No module named 'soundfile'` — the working tree had the extra
# installed from `make install` and hid this completely.
RUN_BENCH := $(UV) run --extra bench
PYTHON_VERSION := 3.12
PATHS := src tests tools scripts

.PHONY: help install fmt lint types test bench-smoke check gate seed-tests run \
        demo probe probe-fake bench bench-live bench-clean metrics report audit clean \
        mutate mutate-selftest

help: ## Show this help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / \
		{printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install: ## Install the pinned toolchain and all extras (and the git hooks)
	$(UV) python install $(PYTHON_VERSION)
	$(UV) sync --frozen --extra dev --extra bench
	$(MAKE) hooks

fmt: ## Format and apply safe lint fixes
	$(RUN) ruff format $(PATHS)
	$(RUN) ruff check --fix $(PATHS)

lint: ## Lint and check formatting
	$(RUN) ruff check $(PATHS)
	$(RUN) ruff format --check $(PATHS)

types: ## Type check (strict; no Any in nod_core)
	$(RUN) mypy

test: ## Run tests with the coverage gate on src/nod_core
	$(RUN) pytest

bench-smoke: ## Assert the harness is addressable (the bench leg of `make check`)
	$(RUN) pytest -m smoke tests/integration/test_bench_smoke.py --no-cov

check: ## The gate: lint, types, tests, bench smoke
	$(MAKE) lint
	$(MAKE) types
	$(MAKE) test
	$(MAKE) bench-smoke

gate: ## The gate, with its exit code preserved. Use this, not `make check | grep`
	@# `make check` is what you want to know about; piping it through grep or
	@# chaining a commit after it in one shell line lets grep's exit code stand
	@# in for the gate's, and a red gate reaches a commit. That has now happened
	@# twice on this repository (CLAUDE.md §5). This target exists so there is
	@# never a reason to pipe: it tees the full log to a file, prints the part
	@# you would have grepped for, and exits with the gate's own status.
	@#
	@# .SHELLFLAGS sets `-o pipefail` for every recipe line here, so the tee
	@# pipeline below cannot swallow a failure the way an interactive shell can.
	@# No pipeline at all, deliberately. `.SHELLFLAGS` cannot be trusted here
	@# (see the note at the top), so the only reliable construction is to
	@# redirect, test the status explicitly, and make the failure path the one
	@# that produces output.
	@rm -f .gate.ok
	@$(MAKE) check > .gate.log 2>&1 || { \
		tail -40 .gate.log; \
		echo; \
		echo "gate: FAILED — full log in .gate.log"; \
		exit 1; \
	}
	@sh tools/gate-stamp.sh > .gate.ok
	@echo
	@grep -E 'passed|Required test coverage' .gate.log | tail -3
	@echo "gate: PASSED"

hooks: ## Install the pre-commit gate-stamp guard
	@# **A shim, not a copy.** `cp` was the original and it silently forks the
	@# guard: `.git/hooks/` is not tracked, so editing `tools/pre-commit` leaves
	@# the running hook untouched until someone remembers to re-run this target.
	@# Gate 4b hit exactly that — the source was fixed to compare only line 1 of
	@# the stamp while the installed copy still compared the whole file, so the
	@# commit was refused over a timestamp. A fix that does not take effect is
	@# worse than no fix, because it reports success.
	@#
	@# `exec`ing the tracked file means the hook is whatever is committed, always.
	@printf '#!/bin/sh\n# Generated by `make hooks`. Do not edit; edit tools/pre-commit.\nexec sh "$$(git rev-parse --show-toplevel)/tools/pre-commit" "$$@"\n' \
		> .git/hooks/pre-commit
	@chmod +x .git/hooks/pre-commit
	@echo "installed .git/hooks/pre-commit (shim -> tools/pre-commit)"

mutate: ## Mutation run over the first-tier modules (CLAUDE.md §5). MODULE=profiler
	$(RUN) python tools/mutate.py $(MODULE)

mutate-selftest: ## Prove the harness can report both of its own failure modes
	@# Expects exit 2: one deliberate survivor and one deliberate unmatched
	@# anchor, which must print in different sections. A harness whose own
	@# failure modes are untested is the CLAUDE.md §5 defect one level up.
	@$(RUN) python tools/mutate.py selftest; \
		status=$$?; \
		if [ $$status -ne 2 ]; then \
			echo "mutate-selftest: FAILED — expected exit 2, got $$status"; \
			exit 1; \
		fi; \
		echo "mutate-selftest: PASSED (exit 2, as required)"

seed-tests: ## Run the `say`-shelling tests, excluded from the default suite
	$(RUN) pytest -m say -p no:cacheprovider

run: ## Serve the API on http://127.0.0.1:8000
	$(RUN) uvicorn --factory nod_server.app:create_app \
		--host 127.0.0.1 --port 8000 --reload

demo: ## Reference intake agent plus console, via docker compose
	docker compose up --build

probe: ## Capability probe against the real API; needs ASSEMBLYAI_API_KEY and SEED
	$(RUN_BENCH) python -m nod_bench.probe --seed-wav $(SEED)

probe-fake: ## Capability probe against the in-memory upstream, zero API spend
	$(RUN_BENCH) python -m nod_bench.probe --fake --quick

bench: ## Full benchmark offline against FakeAssemblyAI, no API key needed
	$(RUN_BENCH) python -m nod_bench.replay --fake --out bench/runs

bench-live: ## Full benchmark against the real API; needs ASSEMBLYAI_API_KEY
	@# --concurrency is passed explicitly and must stay that way. The default is
	@# LIVE_CONCURRENCY = 2, the safe value derived for the *server*, where a
	@# rotating session holds two upstream sockets. It is the wrong model anyway:
	@# Gate 4b established the account limits a *start rate*, not a count, so
	@# --min-interval is the setting that matters and concurrency 1 is enough.
	@# 4 was tried and refused with 1008 within seconds; 16 s at concurrency 1
	@# ran 360/360 clean. Both are passed explicitly because the defaults are the
	@# safe values, not the intended ones, and a default that quadruples a run's
	@# length silently is the same class as a docstring nothing enforces.
	$(RUN_BENCH) python -m nod_bench.replay --live --repeats 5 --concurrency 1 \
		--min-interval 16 --out bench/runs

trackc-check: ## Pilot gate: validate one recording's seams. AUDIO= SCRIPT=
	$(RUN_BENCH) python -m nod_bench.trackc check --audio $(AUDIO) --script $(SCRIPT)

bench-clean: ## Drop the bench result cache (there is none; see below)
	@# **Nothing is cached, and nothing should be.** `replay()`'s original stub
	@# docstring promised `sha256(audio, config, code_version)` keyed results
	@# under `.nodcache/`; the implementation at Gate 4a did not build it and the
	@# promise went with the stub. Gate 4b confirmed: no `code_version` exists
	@# anywhere in the tree, no `.nodcache/` is ever written, and no session in
	@# the live sweep came from one.
	@#
	@# It stays unbuilt deliberately. **Caching a live run would defeat N=5.**
	@# BENCH_SPEC §4 repeats a (clip, arm) pair five times precisely because the
	@# upstream is non-deterministic; five repeats served from one cache entry
	@# would be byte-identical and their IQR exactly zero, which is the
	@# precision-by-determinism defect ADR-019 exists to prevent. The sweep is
	@# rate-limited by the account, not compute-limited, so a cache would buy
	@# nothing and cost the variance measurement.
	rm -rf .nodcache

metrics: ## Recompute every metric from committed traces, zero API spend
	$(RUN_BENCH) python -m nod_bench.metrics --runs bench/runs

report: ## Render the self-contained HTML report card
	$(RUN_BENCH) python -m nod_bench.report --runs bench/runs --out bench/report.html

deck: ## Render docs/deck.html to docs/nod-deck.pdf (needs Google Chrome)
	@# Chrome headless rather than a Python PDF library: the deck embeds the
	@# timeline SVGs that `pilot_ladder.py svg` writes, and rendering them
	@# anywhere other than a browser would mean a second renderer that could
	@# disagree with the one in the video.
	"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
	  --headless --disable-gpu --no-pdf-header-footer \
	  --print-to-pdf=docs/nod-deck.pdf docs/deck.html
	@echo "wrote docs/nod-deck.pdf"

cover: ## Render docs/cover.html to docs/nod-cover.png (16:9 submission cover)
	"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
	  --headless --disable-gpu --hide-scrollbars --window-size=1280,720 \
	  --screenshot=docs/nod-cover.png docs/cover.html
	@echo "wrote docs/nod-cover.png"

audit: ## Check dependencies for known vulnerabilities
	$(RUN) pip-audit --strict

clean: ## Remove tooling caches and build output
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage coverage.xml \
		htmlcov dist build
	find . -name __pycache__ -type d -prune -exec rm -rf {} +
