"""Render the results table, the Pareto chart and the report card.

INV-9: no number in any document is hand-written. Every figure in the README,
docs/RESULTS.md or a slide is generated here from committed traces.
"""

from __future__ import annotations

import html
import re
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Final, Literal

import numpy as np
from pydantic import BaseModel, ConfigDict

from nod_bench.metrics import (
    LIVE_TAG,
    QUANTILE_METHOD,
    SIMULATED_TAG,
    ClipObservation,
    RunManifest,
    artifact_name,
    frag,
    pcr,
    ttl,
)
from nod_bench.replay import Arm, RunResult

BOOTSTRAP_REPLICATES: Final = 10_000
"""`B` for the clip bootstrap (ADR-019)."""

BOOTSTRAP_SEED: Final = 20260917
"""Fixed, so the chart is reproducible from the same observations."""

CI_PERCENTILES: Final = (2.5, 97.5)
"""A 95 % percentile interval."""

type IntervalKind = Literal[
    "bootstrap-ci-over-clips",
    "iqr-over-repeats",
    "cluster-bootstrap-over-clips",
]
"""Which statistic an `ArmPoint`'s interval holds. See `ArmPoint.interval_kind`."""

BAR_LABEL: Final = "bars: 95% bootstrap CI over clips (B=10,000), NOT over repeats"
"""Rendered into the chart itself, not into a caption.

A caption does not survive a screenshot and a zero-width bar reads as precision
(ADR-019). Whoever sees the image sees what the bars mean.

**It no longer says "which are zero-width on a deterministic simulator".** That
clause was true of the path it was written for and false on the one that now
also uses it: a *live* run with `repeats=1` has no repeat axis either, and
falls back to this same bootstrap. The label was then asserting the simulator
on a live table (observed at Gate 4b). The reason repeats are unavailable
belongs in the run's own provenance line, which knows which it is, not baked
into a constant that cannot tell.
"""

LIVE_BAR_LABEL: Final = (
    "bars: interquartile range over N live repeats (BENCH_SPEC 4) - "
    "NOT a bootstrap over clips"
)
"""The live counterpart. Both are rendered into the image for ADR-019's reason."""

CLUSTER_BAR_LABEL: Final = (
    "bars: 95% cluster bootstrap over clips (B=10,000), clips resampled whole "
    "with all their repeats - covers BOTH which clips were drawn and "
    "run-to-run variation"
)
"""The live default (ADR-049). Wider than either single-source interval."""

BAR_LABELS: Final[dict[IntervalKind, str]] = {
    "bootstrap-ci-over-clips": BAR_LABEL,
    "iqr-over-repeats": LIVE_BAR_LABEL,
    "cluster-bootstrap-over-clips": CLUSTER_BAR_LABEL,
}
"""So a chart cannot be drawn with the wrong label for its own statistic."""

IQR_PERCENTILES: Final = (25.0, 75.0)
"""The interquartile range BENCH_SPEC §4 asks for on the live path."""

MIN_REPEATS_FOR_IQR: Final = 2
"""Below this an IQR is zero-width, which ADR-019 forbids reporting."""

RESULTS_HEADER: Final = """# Nod — Results

<!-- Generated by `python -m nod_bench.report --publish`. Do not edit by hand.
     INV-9: no number in any document is hand-written. Every figure below comes
     from a live run's committed artifacts. -->

"""
"""Preamble for `docs/RESULTS.md`, stating that the file is generated."""

HONEST_SCOPE_HTML: Final = """<h3>Prior art and honest scope</h3>
<p>AssemblyAI's Voice Agent API already ships semantic end-of-turn, semantic
barge-in, and adaptive pacing that adjusts to each speaker over a call. Nod is
not the first adaptive endpointer. It is an open one on the Realtime STT path
with a published policy and published numbers.</p>
<p>Published turn-taking benchmarks already exist, including Full-Duplex-Bench
v3, EVA-Bench, IHBench and &tau;-Voice. Metric definitions borrowed from them are
cited in BENCH_SPEC &sect;5.</p>
<p>What Nod adds is a closed loop: existing benchmarks measure models offline and
stop, and Nod feeds the measurement back into a live session through mid-stream
reconfiguration.</p>
<p><strong>The claim is not that Nod is uniformly faster or uniformly more
accurate.</strong> It is that a single static configuration traces a fixed
tradeoff curve between cutting people off and feeling slow, and a per-caller
controller sits off that curve.</p>
<p>Nod adapts to pauses. It does not interpret them: nothing here infers intent,
emotion, honesty or any clinical condition from pause length.</p>"""
"""CLAUDE.md §8, verbatim in substance. Rendered into the card, not linked.

In the card rather than behind a link because a shareable one-page artifact is
exactly where the scope section is most likely to be dropped and least likely
to be chased.
"""

REPORT_CARD_HTML: Final = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Nod — report card</title>
<style>
 :root {{ color-scheme: light dark; }}
 body {{ font: 15px/1.55 ui-sans-serif, system-ui, sans-serif; max-width: 52rem;
        margin: 3rem auto; padding: 0 1.25rem; }}
 table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
 th, td {{ text-align: left; padding: .4rem .6rem;
           border-bottom: 1px solid
             color-mix(in srgb, currentColor 18%, transparent); }}
 th {{ font-weight: 600; }}
 code {{ font: 13px ui-monospace, monospace; }}
 .note {{ opacity: .78; font-size: 13.5px; margin: .3rem 0; }}
 svg {{ max-width: 100%; height: auto; }}
</style></head><body>
<h1>Nod — report card</h1>
{chart}
{table}
{scope}
</body></html>
"""
"""The card shell. No external assets and no network on open (BENCH_SPEC §8)."""

README_TABLE_START: Final = "<!-- BENCH_TABLE_START -->"
README_TABLE_END: Final = "<!-- BENCH_TABLE_END -->"
"""The machine-owned region of the README. INV-9's enforcement point."""


class ArmPoint(BaseModel):
    """One arm plotted on the headline chart (BENCH_SPEC.md §6)."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    arm: Arm
    pcr: float
    ttl_p90_ms: float
    pcr_ci: tuple[float, float]
    ttl_p90_ci_ms: tuple[float, float]
    """The interval, whose meaning depends on `interval_kind`.

    Named `_ci` rather than `_iqr` because the two are not interchangeable and
    the earlier name would have described the wrong statistic (ADR-019). It now
    carries both, so `interval_kind` is what says which — a field rather than a
    convention, because the two answer different questions and a reader cannot
    tell them apart from the numbers.
    """

    interval_kind: IntervalKind
    """Which statistic `_ci` holds, and therefore what it answers (ADR-045).

    `bootstrap-ci-over-clips` answers "if the generator had produced a different
    corpus, how much would this move" — the only question available against a
    deterministic simulator, where the repeat axis has zero width by construction.
    `iqr-over-repeats` answers "how repeatable is this measurement", which is
    BENCH_SPEC §4's question and is only answerable live.
    """

    n_clips: int
    n_repeats: int = 1
    """Repeats behind the point. 1 on the simulated path (ADR-019)."""

    frag: float


def bootstrap_points(
    by_arm: dict[Arm, list[ClipObservation]],
    *,
    replicates: int = BOOTSTRAP_REPLICATES,
    seed: int = BOOTSTRAP_SEED,
) -> list[ArmPoint]:
    """Point estimates with clip-bootstrap intervals. `O(B * arms * clips)`.

    Clips are resampled **jointly across arms** inside each replicate, so the
    paired structure BENCH_SPEC §9 relies on survives and an arm-to-arm
    difference could be bootstrapped the same way.

    Args:
        by_arm: Observations per arm, all over the same clips in the same order.
        replicates: `B`.
        seed: Fixed so the chart is reproducible.

    Returns:
        One point per arm.

    Raises:
        ValueError: The arms do not cover the same clips.
    """
    arms = list(by_arm)
    if not arms:
        msg = "no arms to plot"
        raise ValueError(msg)
    n_clips = len(by_arm[arms[0]])
    for arm in arms:
        if [o.clip_id for o in by_arm[arm]] != [o.clip_id for o in by_arm[arms[0]]]:
            msg = f"arm {arm!r} was not run over the same clips, so pairing is lost"
            raise ValueError(msg)

    rng = np.random.default_rng(seed)
    draws = rng.integers(0, n_clips, size=(replicates, n_clips))
    samples: dict[Arm, tuple[list[float], list[float]]] = {
        arm: ([], []) for arm in arms
    }
    for replicate in draws:
        for arm in arms:
            picked = [by_arm[arm][int(i)] for i in replicate]
            samples[arm][0].append(pcr(picked))
            samples[arm][1].append(ttl(picked).p90)

    points: list[ArmPoint] = []
    for arm in arms:
        pcr_draws, ttl_draws = samples[arm]
        lo, hi = CI_PERCENTILES
        points.append(
            ArmPoint(
                arm=arm,
                pcr=pcr(by_arm[arm]),
                ttl_p90_ms=ttl(by_arm[arm]).p90,
                pcr_ci=(
                    float(np.percentile(pcr_draws, lo)),
                    float(np.percentile(pcr_draws, hi)),
                ),
                ttl_p90_ci_ms=(
                    float(np.percentile(ttl_draws, lo)),
                    float(np.percentile(ttl_draws, hi)),
                ),
                interval_kind="bootstrap-ci-over-clips",
                n_clips=n_clips,
                n_repeats=1,
                frag=frag(by_arm[arm]),
            )
        )
    return points


def repeat_points(
    by_arm: dict[Arm, list[ClipObservation]], *, repeats: int
) -> list[ArmPoint]:
    """Point estimates with an interquartile range over repeats. `O(arms * n)`.

    The live counterpart to `bootstrap_points`, and **deliberately not a branch
    inside it** (ADR-045). The two compute different statistics answering
    different questions, and ADR-019's reasoning for the bootstrap holds only
    where the repeat axis has zero width. Unifying them would need a flag
    threaded through the resampling, and the first person to read it would have
    to reconstruct which half applied.

    Each arm's observations arrive as `clips x repeats`, grouped by clip: repeat
    `r` of every clip forms one *pass*, the whole corpus measured once. PCR and
    TTL p90 are computed per pass, and the median and IQR are taken across the
    `repeats` passes. Aggregating the other way — per clip across repeats, then
    pooling — would answer "how variable is one clip" and BENCH_SPEC §4 asks for
    the spread of the *result*.

    Args:
        by_arm: Observations per arm, `clips x repeats`, grouped by clip.
        repeats: `N`. Must divide each arm's observation count exactly.

    Returns:
        One point per arm, with `interval_kind="iqr-over-repeats"`.

    Raises:
        ValueError: `repeats` does not divide the observations, the arms do not
            cover the same clips, or `repeats` is below 2 — an IQR over one
            repeat is zero-width, which is the precision-by-determinism defect
            ADR-019 exists to prevent.
    """
    arms = list(by_arm)
    if not arms:
        msg = "no arms to plot"
        raise ValueError(msg)
    if repeats < MIN_REPEATS_FOR_IQR:
        msg = (
            f"repeat_points needs at least {MIN_REPEATS_FOR_IQR} repeats, got "
            f"{repeats}: an IQR over one pass is exactly zero and a zero-width "
            f"bar reads as precision (ADR-019). Use bootstrap_points instead."
        )
        raise ValueError(msg)
    for arm in arms:
        if len(by_arm[arm]) % repeats:
            msg = (
                f"arm {arm!r} carries {len(by_arm[arm])} observations, which "
                f"{repeats} repeats do not divide: the passes cannot be recovered"
            )
            raise ValueError(msg)
        if [o.clip_id for o in by_arm[arm]] != [o.clip_id for o in by_arm[arms[0]]]:
            msg = f"arm {arm!r} was not run over the same clips, so pairing is lost"
            raise ValueError(msg)

    points: list[ArmPoint] = []
    lo, hi = IQR_PERCENTILES
    for arm in arms:
        observations = by_arm[arm]
        passes = [observations[r::repeats] for r in range(repeats)]
        pcr_draws = [pcr(p) for p in passes]
        ttl_draws = [ttl(p).p90 for p in passes]
        points.append(
            ArmPoint(
                arm=arm,
                pcr=float(np.median(pcr_draws)),
                ttl_p90_ms=float(np.median(ttl_draws)),
                pcr_ci=(
                    float(np.percentile(pcr_draws, lo)),
                    float(np.percentile(pcr_draws, hi)),
                ),
                ttl_p90_ci_ms=(
                    float(np.percentile(ttl_draws, lo)),
                    float(np.percentile(ttl_draws, hi)),
                ),
                interval_kind="iqr-over-repeats",
                n_clips=len(observations) // repeats,
                n_repeats=repeats,
                frag=frag(observations),
            )
        )
    return points


def cluster_bootstrap_points(
    by_arm: dict[Arm, list[ClipObservation]],
    *,
    repeats: int,
    replicates: int = BOOTSTRAP_REPLICATES,
    seed: int = BOOTSTRAP_SEED,
) -> list[ArmPoint]:
    """Interval over both variance sources at once. `O(B * arms * n)`.

    **The live default since ADR-049, and the reason is the subsample.** Live
    results carry two independent uncertainties: which clips the generator
    happened to produce, and how the service happened to respond on the day.
    `bootstrap_points` measures only the first and `repeat_points` only the
    second, and each was right for the run it was written for — the simulated
    sweep has no second source, and a 120-clip live sweep would have a first
    source small enough to leave implicit.

    At **n = 12** neither holds. The clip axis is a tenth of the design and is
    now the dominant term, so `repeat_points`' IQR over five whole-corpus passes
    understates the interval by ignoring it entirely.

    Clips are resampled **whole** — drawing a clip takes all of its repeats —
    which is the standard estimator for clustered observations and keeps the
    repeat variation inside the replicate instead of averaging it away. Clips
    are drawn **jointly across arms** within a replicate, so BENCH_SPEC §9's
    pairing survives exactly as in `bootstrap_points`.

    Args:
        by_arm: Observations per arm, `clips x repeats`, grouped by clip.
        repeats: `N`, checked against every cluster's size.
        replicates: `B`.
        seed: Fixed, so the chart is reproducible.

    Returns:
        One point per arm, `interval_kind="cluster-bootstrap-over-clips"`.

    Raises:
        ValueError: The arms do not cover the same clips, or some clip does not
            carry exactly `repeats` observations.
    """
    arms = list(by_arm)
    if not arms:
        msg = "no arms to plot"
        raise ValueError(msg)
    for arm in arms:
        if [o.clip_id for o in by_arm[arm]] != [o.clip_id for o in by_arm[arms[0]]]:
            msg = f"arm {arm!r} was not run over the same clips, so pairing is lost"
            raise ValueError(msg)

    order: list[str] = []
    groups: dict[Arm, dict[str, list[ClipObservation]]] = {a: {} for a in arms}
    for arm in arms:
        for obs in by_arm[arm]:
            if arm == arms[0] and obs.clip_id not in groups[arm]:
                order.append(obs.clip_id)
            groups[arm].setdefault(obs.clip_id, []).append(obs)
    n_clips = len(order)
    for arm in arms:
        sizes = {len(v) for v in groups[arm].values()}
        if sizes != {repeats}:
            msg = (
                f"arm {arm!r} has clips with {sorted(sizes)} repeats, expected "
                f"{repeats} each: the clusters are uneven, and a whole-clip "
                f"resample would then weight them unequally"
            )
            raise ValueError(msg)

    rng = np.random.default_rng(seed)
    draws = rng.integers(0, n_clips, size=(replicates, n_clips))
    samples: dict[Arm, tuple[list[float], list[float]]] = {a: ([], []) for a in arms}
    for replicate in draws:
        picked_ids = [order[int(i)] for i in replicate]
        for arm in arms:
            picked = [obs for cid in picked_ids for obs in groups[arm][cid]]
            samples[arm][0].append(pcr(picked))
            samples[arm][1].append(ttl(picked).p90)

    lo, hi = CI_PERCENTILES
    points: list[ArmPoint] = []
    for arm in arms:
        pcr_draws, ttl_draws = samples[arm]
        flat = by_arm[arm]
        points.append(
            ArmPoint(
                arm=arm,
                pcr=pcr(flat),
                ttl_p90_ms=ttl(flat).p90,
                pcr_ci=(
                    float(np.percentile(pcr_draws, lo)),
                    float(np.percentile(pcr_draws, hi)),
                ),
                ttl_p90_ci_ms=(
                    float(np.percentile(ttl_draws, lo)),
                    float(np.percentile(ttl_draws, hi)),
                ),
                interval_kind="cluster-bootstrap-over-clips",
                n_clips=n_clips,
                n_repeats=repeats,
                frag=frag(flat),
            )
        )
    return points


def pareto_svg(points: Sequence[ArmPoint]) -> str:
    """Render the headline chart as hand-rolled SVG.

    PCR on the y axis, TTL p90 on the x axis. The three static arms trace the
    tradeoff curve; Nod is a point with error bars. Hand-rolled rather than
    charted because Recharts styling fights the glass system (CLAUDE.md §3).

    Args:
        points: One point per arm.

    Returns:
        The SVG document.
    """
    width, height = 720, 460
    left, right, top, bottom = 82, 28, 56, 96
    xs = [p.ttl_p90_ci_ms[1] for p in points] + [p.ttl_p90_ms for p in points]
    x_max = max(xs) * 1.08 if xs else 1.0
    y_max = 1.0

    def sx(value: float) -> float:
        return left + (value / x_max) * (width - left - right)

    def sy(value: float) -> float:
        return top + (1.0 - value / y_max) * (height - top - bottom)

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
        f'height="{height}" viewBox="0 0 {width} {height}" '
        f'font-family="ui-sans-serif, system-ui, sans-serif">',
        f'<rect width="{width}" height="{height}" fill="#0b0f14"/>',
        f'<text x="{left}" y="26" fill="#e6edf3" font-size="15" '
        f'font-weight="600">Premature cutoff rate vs turn latency</text>',
        f'<text x="{left}" y="44" fill="#f0b429" font-size="11">'
        f"SIMULATED - not a measurement of AssemblyAI</text>",
    ]
    parts.append(
        f'<line x1="{left}" y1="{sy(0)}" x2="{width - right}" y2="{sy(0)}" '
        f'stroke="#30363d"/>'
    )
    parts.append(
        f'<line x1="{left}" y1="{top}" x2="{left}" y2="{sy(0)}" stroke="#30363d"/>'
    )
    parts.extend(
        f'<text x="{left - 10}" y="{sy(tick) + 4}" fill="#8b949e" '
        f'font-size="10" text-anchor="end">{tick:.2f}</text>'
        for tick in (0.0, 0.25, 0.5, 0.75, 1.0)
    )
    for point in points:
        x, y = sx(point.ttl_p90_ms), sy(point.pcr)
        parts.append(
            f'<line x1="{sx(point.ttl_p90_ci_ms[0])}" y1="{y}" '
            f'x2="{sx(point.ttl_p90_ci_ms[1])}" y2="{y}" stroke="#58a6ff" '
            f'stroke-width="2" opacity="0.75"/>'
        )
        parts.append(
            f'<line x1="{x}" y1="{sy(point.pcr_ci[0])}" x2="{x}" '
            f'y2="{sy(point.pcr_ci[1])}" stroke="#58a6ff" stroke-width="2" '
            f'opacity="0.75"/>'
        )
        parts.append(f'<circle cx="{x}" cy="{y}" r="5" fill="#58a6ff"/>')
        parts.append(
            f'<text x="{x + 10}" y="{y - 8}" fill="#e6edf3" font-size="11">'
            f"{point.arm}</text>"
        )
    parts.append(
        f'<text x="{(left + width - right) / 2}" y="{height - 58}" '
        f'fill="#8b949e" font-size="11" text-anchor="middle">'
        f"TTL p90 (ms), {QUANTILE_METHOD}</text>"
    )
    parts.append(
        f'<text x="18" y="{(top + sy(0)) / 2}" fill="#8b949e" font-size="11" '
        f'text-anchor="middle" transform="rotate(-90 18 {(top + sy(0)) / 2})">'
        f"PCR</text>"
    )
    parts.append(
        f'<text x="{left}" y="{height - 34}" fill="#8b949e" font-size="10">'
        f"{BAR_LABEL}</text>"
    )
    n = points[0].n_clips if points else 0
    parts.append(
        f'<text x="{left}" y="{height - 18}" fill="#8b949e" font-size="10">'
        f"n={n} clips, one synthetic voice: the interval is a lower bound on "
        f"uncertainty (ADR-018, ADR-019)</text>"
    )
    parts.append("</svg>")
    return "\n".join(parts)


INCONCLUSIVE: Final = "inconclusive"
"""EC-38's required word, used verbatim so a grep for it finds every instance."""


def inconclusive_pairs(
    points: Sequence[ArmPoint], *, baseline: Arm = "balanced"
) -> list[str]:
    """Arms whose interval is wider than their distance from `baseline`. `O(n)`.

    EC-38: "Report `inconclusive` in those words. Never present a difference
    smaller than the noise." This was documented in `render_results_md`'s
    docstring and implemented nowhere, which is worse than absent — the docstring
    read as coverage (CLAUDE.md §5).

    Compared on **TTL p90**, the x axis of the headline chart, because that is
    the axis the latency claim is made on. An arm can be conclusive on one axis
    and not the other, so the returned reason names the axis.

    Args:
        points: One point per arm.
        baseline: The arm to compare against. `balanced` is the documented
            AssemblyAI default and BENCH_SPEC §3's headline baseline.

    Returns:
        One human-readable line per inconclusive arm, empty when all are clear.
    """
    reference = next((p for p in points if p.arm == baseline), None)
    if reference is None:
        return []
    lines: list[str] = []
    for point in points:
        if point.arm == baseline:
            continue
        difference = abs(point.ttl_p90_ms - reference.ttl_p90_ms)
        width = point.ttl_p90_ci_ms[1] - point.ttl_p90_ci_ms[0]
        if width > difference:
            lines.append(
                f"`{point.arm}` vs `{baseline}` on TTL p90 is **{INCONCLUSIVE}**: "
                f"the difference is {difference:.0f} ms and the interval spans "
                f"{width:.0f} ms ({point.interval_kind})."
            )
    return lines


def track_disagreements(
    track_a: Sequence[ArmPoint], track_c: Sequence[ArmPoint], *, baseline: Arm
) -> list[str]:
    """Arms that move in opposite directions on the two tracks. `O(n)`.

    EC-41: "If Track A and Track C disagree in direction, both are reported
    prominently." Also documented and unimplemented before Gate 4a.

    Direction is the sign of `arm - baseline` on TTL p90. A sign flip between
    tracks is the finding that matters: it means the corpus, not the controller,
    decided the headline, and averaging the two would hide it completely.

    Args:
        track_a: Points from the Track A sweep.
        track_c: Points from the Track C sweep.
        baseline: The arm both are measured against.

    Returns:
        One line per disagreeing arm, empty when every arm agrees.
    """

    def deltas(points: Sequence[ArmPoint]) -> dict[Arm, float]:
        reference = next((p for p in points if p.arm == baseline), None)
        if reference is None:
            return {}
        return {
            p.arm: p.ttl_p90_ms - reference.ttl_p90_ms
            for p in points
            if p.arm != baseline
        }

    a_deltas, c_deltas = deltas(track_a), deltas(track_c)
    lines: list[str] = []
    for arm in sorted(set(a_deltas) & set(c_deltas)):
        a, c = a_deltas[arm], c_deltas[arm]
        if a == 0.0 or c == 0.0 or (a > 0) == (c > 0):
            continue
        lines.append(
            f"**`{arm}` disagrees in direction between tracks**: "
            f"{a:+.0f} ms against `{baseline}` on Track A, {c:+.0f} ms on "
            f"Track C. The sign is a property of the corpus, not of the arm."
        )
    return lines


SPECIFIED_CLIPS: Final = 120
"""Track A's committed clip count, which BENCH_SPEC's sweep is specified over.

Stated so a table generated from a subsample can say what it is a subsample
*of*, without the reader having to know.
"""

UNMEASURABLE_METRICS: Final = ("TCT", "RES")
"""BENCH_SPEC §5 rows that refuse on a replay corpus (ADR-046).

Named in the generated footer rather than only in prose: a reader comparing
against a benchmark that publishes seven metrics can otherwise only conclude
that two were dropped quietly.
"""


def render_results_md(
    points: Sequence[ArmPoint],
    *,
    other_track: Sequence[ArmPoint] | None = None,
    manifest: RunManifest | None = None,
) -> str:
    """Render the arm table with its intervals, and the two required warnings.

    The interval's meaning comes from `points[0].interval_kind`: a bootstrap over
    clips on the simulated path (ADR-019), an IQR over repeats live (ADR-045).
    The column heading and the bar label both follow it, so a live table cannot
    be printed under a simulated legend.

    Both warnings are **implemented** as of Gate 4a, and were not before: an
    interval wider than the arm-to-arm difference is reported as `inconclusive`
    in that word (EC-38), and an arm whose direction flips between tracks is
    reported prominently (EC-41). This docstring asserted both while the body did
    neither, which is the CLAUDE.md §5 shape — a claim that reads as coverage.

    **The caveats are generated into the document, not written above it**
    (Gate 4b). A table leaves this repository as a screenshot far more often
    than as a file, and a screenshot carries none of the prose around it. So
    provenance, the subsample size against the specified sweep, the corpus, and
    the two metrics that refuse all travel in the footer that `manifest`
    supplies.

    Args:
        points: One point per arm.
        other_track: The other track's points, for EC-41. Omitted when only one
            track has been run, which is the state until Track C is recorded.
        manifest: The run manifest, for the provenance footer. Omitted only by
            callers that have none; the footer is then shorter, never wrong.

    Returns:
        The markdown document.
    """
    kind = points[0].interval_kind if points else "bootstrap-ci-over-clips"
    heading = "95% CI" if kind == "bootstrap-ci-over-clips" else "IQR"
    lines = [
        f"| arm | PCR | {heading} | TTL p90 (ms) | {heading} | FRAG |",
        "|---|---|---|---|---|---|",
    ]
    lines.extend(
        f"| `{point.arm}` | {point.pcr:.3f} | "
        f"[{point.pcr_ci[0]:.3f}, {point.pcr_ci[1]:.3f}] | "
        f"{point.ttl_p90_ms:.0f} | "
        f"[{point.ttl_p90_ci_ms[0]:.0f}, {point.ttl_p90_ci_ms[1]:.0f}] | "
        f"{point.frag:.3f} |"
        for point in points
    )
    lines.append("")
    lines.append(f"{BAR_LABELS[kind]}.")
    if kind == "bootstrap-ci-over-clips" and points and points[0].n_repeats == 1:
        lines.append(
            "Single pass per clip, so there is no repeat axis to report a spread "
            "over; against the simulator that is by design (ADR-019), and on a "
            "live run it means BENCH_SPEC §4's N was not met."
        )
    lines.append(
        f"Percentiles are {QUANTILE_METHOD}. n={points[0].n_clips if points else 0} "
        f"clips"
        + (
            f" x {points[0].n_repeats} repeats"
            if points and points[0].n_repeats > 1
            else ""
        )
        + " from one synthetic voice; the interval is a lower bound on "
        "uncertainty (ADR-018, ADR-019)."
    )

    if manifest is not None:
        lines.extend(_provenance_footer(points, manifest))

    flagged = inconclusive_pairs(points)
    if flagged:
        lines.extend(["", f"### {INCONCLUSIVE.capitalize()} comparisons (EC-38)", ""])
        lines.extend(f"- {line}" for line in flagged)
    if other_track is not None:
        clashes = track_disagreements(points, other_track, baseline="balanced")
        if clashes:
            lines.extend(["", "### Track disagreement (EC-41)", ""])
            lines.extend(f"- {line}" for line in clashes)
    return "\n".join(lines)


def _provenance_footer(
    points: Sequence[ArmPoint] | None, manifest: RunManifest
) -> list[str]:
    """The lines a screenshot of the table has to carry with it. Pure. `O(1)`.

    `points` is optional so `main` can build the same footer from a manifest
    alone, for a run whose points were rendered by an earlier process.
    """
    live = not manifest.simulated
    clips = points[0].n_clips if points else manifest.corpus_clips
    lines = [""]
    if live:
        lines.append(
            f"**Live run** against the streaming API, `{manifest.corpus_id}`, "
            f"{clips} clips x {manifest.repeats_per_arm} repeats x "
            f"{len(manifest.arms)} arms."
        )
        if clips < SPECIFIED_CLIPS:
            lines.append(
                f"**Subsample: {clips} of {SPECIFIED_CLIPS} clips.** The account "
                f"permits roughly one new session every 15 s once a closed "
                f"session's slot is counted, which puts the specified sweep at "
                f"about 16 hours (ADR-048). **n is a tenth of the design**, so "
                f"the clip axis — which clips happened to be drawn — dominates "
                f"the uncertainty here."
            )
    else:
        lines.append(
            f"**Simulated** against `FakeAssemblyAI`, `{manifest.corpus_id}`, "
            f"{clips} clips. Not a measurement of AssemblyAI (ADR-017)."
        )
    lines.append(
        "Corpus is synthetic speech from one macOS `say` voice, whose own "
        "manifest states it is not adequate for a published number; see the "
        "README's honest-scope section."
    )
    lines.append(
        f"{' and '.join(UNMEASURABLE_METRICS)} are **not reported**: both need "
        f"a caller who reacts to being cut off, and recorded audio does not "
        f"(ADR-046)."
    )
    lines.append(
        f"Endpoint overhead {manifest.endpoint_overhead_ms:.0f} ms; "
        f"percentiles {manifest.quantile_method}."
    )
    lines.extend(_pcr_anchor_caveat(live))
    return lines


PCR_ANCHOR_CAVEAT: Final = (
    "> **PCR is unreliable on a live run, and by more than it looks.** Deciding "
    "whether a boundary was premature means deciding which ground-truth gap it "
    "fell in, and live that lookup uses `emitted_silence_start_ms` — the "
    "service's last-word timing, because the service does not report where it "
    "started counting silence (ADR-036). Gate 4e measured that field against "
    "the audio and it is not a clock offset that could be subtracted out: on "
    "one clip it puts the prefix's end **560 ms late** and the continuation's "
    "**190-250 ms early**, in the same session. Track A's gaps are 100-2200 ms, "
    "so an error that size moves boundaries between neighbouring gaps and "
    "**every PCR figure above may be attributed to the wrong gap** (ADR-055). "
    "TTL and FRAG do not use the field and are unaffected. Not fixed; the "
    "figures are left standing and labelled rather than withdrawn, because the "
    "size of the error is known and its direction is not."
)
"""Why a live PCR figure cannot be read at face value (ADR-055).

Generated into the footer rather than written into README.md by hand, because
INV-9 owns every number-adjacent claim in that region and a caveat typed beside
a machine-written table is the first thing to drift away from it.
"""


def _pcr_anchor_caveat(live: bool) -> list[str]:
    """The PCR anchor warning, on live runs only. Pure. `O(1)`.

    Simulated runs are exempt and that is a real distinction rather than an
    oversight: `FakeAssemblyAI` reports the silence start it actually used, so
    the simulated lookup is exact. The defect is a property of the real
    service's word-timing field, so it attaches to the runs that touched it.

    Args:
        live: Whether this run went against the real API.

    Returns:
        The caveat lines, or empty for a simulated run.
    """
    return ["", PCR_ANCHOR_CAVEAT] if live else []


def render_all(
    by_arm: dict[Arm, list[ClipObservation]],
    *,
    out: Path,
    simulated: bool,
    manifest: RunManifest,
    repeats: int = 1,
) -> list[Path]:
    """Write every artifact for one run, each labelled with its provenance.

    ADR-016 and ADR-017: `simulated` appears in the filename as well as in the
    manifest, because a chart leaves the repository as an image and a caption
    does not survive a screenshot.

    Args:
        by_arm: Observations per arm over the same clips.
        out: Output directory.
        simulated: Whether a simulator produced these.
        manifest: The run manifest, written alongside.
        repeats: `N`. Above 1 the interval becomes an IQR over repeats rather
            than a bootstrap over clips (ADR-045).

    Returns:
        The paths written.

    Raises:
        ValueError: `repeats` above 1 on a simulated run. The simulator is
            deterministic, so those repeats are byte-identical and their IQR is
            exactly zero — reporting it would present determinism as precision,
            which is the defect ADR-019 was written for.
    """
    if simulated and repeats > 1:
        msg = (
            f"render_all(simulated=True, repeats={repeats}): repeats against the "
            "simulator are byte-identical, so their IQR is 0 and a zero-width bar "
            "reads as precision (ADR-019). The simulated path uses the clip "
            "bootstrap; only --live has a repeat axis."
        )
        raise ValueError(msg)
    out.mkdir(parents=True, exist_ok=True)
    points = (
        cluster_bootstrap_points(by_arm, repeats=repeats)
        if repeats > 1
        else bootstrap_points(by_arm)
    )
    written: list[Path] = []
    for stem, suffix, payload in (
        ("pareto", "svg", pareto_svg(points)),
        ("results", "md", render_results_md(points, manifest=manifest)),
        ("manifest", "json", manifest.model_dump_json(indent=1)),
    ):
        path = out / artifact_name(stem, simulated=simulated, suffix=suffix)
        path.write_text(payload)
        written.append(path)
    tag = SIMULATED_TAG if simulated else LIVE_TAG
    unlabelled = [p.name for p in written if tag not in p.name]
    if unlabelled:
        msg = f"artifacts escaped without a provenance tag: {unlabelled}"
        raise AssertionError(msg)
    return written


def render_report_card(runs: Sequence[RunResult]) -> str:
    """Render the one-page shareable report card.

    A single self-contained HTML file: the Pareto chart, the arm table with IQRs,
    ablation deltas, the corpus manifest and the honest-scope section. No
    external assets, no network on open (BENCH_SPEC.md §8).

    Args:
        runs: Every run in the sweep.

    Returns:
        The HTML document.

    Raises:
        ValueError: No run carries an observation, so there is nothing to render.
    """
    by_arm: dict[Arm, list[ClipObservation]] = {}
    repeats = max((run.repeats for run in runs), default=1)
    for run in sorted(runs, key=lambda r: (r.arm, r.clip_id)):
        by_arm.setdefault(run.arm, []).extend(run.observations)
    if not any(by_arm.values()):
        msg = (
            f"render_report_card over {len(runs)} runs carrying no observations: "
            "an empty card would still render a chart and a table, and both would "
            "be about nothing"
        )
        raise ValueError(msg)
    points = (
        cluster_bootstrap_points(by_arm, repeats=repeats)
        if repeats > 1
        else bootstrap_points(by_arm)
    )
    table = render_results_md(points)
    return REPORT_CARD_HTML.format(
        chart=pareto_svg(points),
        table=_markdown_table_to_html(table),
        scope=HONEST_SCOPE_HTML,
    )


def update_readme_table(readme: Path, table: str) -> None:
    """Replace the machine-owned region of the README with a generated table.

    Writes between `README_TABLE_START` and `README_TABLE_END` and touches
    nothing else. This is how INV-9 is kept: the table region is owned by
    `make bench`, not by whoever is editing prose.

    Args:
        readme: Path to the README.
        table: The generated markdown table.

    Raises:
        ValueError: A marker is missing, or they appear in the wrong order, or
            either appears more than once. All four are refusals rather than
            best-effort writes: a marker pair that cannot be located exactly is
            a README whose table region is not machine-owned, and silently
            appending would leave a hand-written number in place while reporting
            success.
    """
    text = readme.read_text(encoding="utf-8")
    for marker in (README_TABLE_START, README_TABLE_END):
        found = text.count(marker)
        if found != 1:
            msg = (
                f"{readme} contains {found} copies of {marker!r}, expected "
                f"exactly 1: INV-9 needs one unambiguous machine-owned region"
            )
            raise ValueError(msg)
    start = text.index(README_TABLE_START)
    end = text.index(README_TABLE_END)
    if start > end:
        msg = (
            f"{readme}: {README_TABLE_START!r} appears after "
            f"{README_TABLE_END!r}, so the region is inverted"
        )
        raise ValueError(msg)
    readme.write_text(
        text[: start + len(README_TABLE_START)]
        + "\n"
        + table.strip()
        + "\n"
        + text[end:],
        encoding="utf-8",
    )


def _markdown_table_to_html(markdown: str) -> str:
    """The generated markdown, as minimal HTML. Pure. `O(n)`.

    Hand-rolled rather than a dependency: the input is this module's own output,
    so the grammar is three shapes — a pipe row, a separator, a paragraph — and a
    markdown library would be a wheel to render a table we wrote ourselves.
    """
    out: list[str] = []
    in_table = False
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(set(c) <= {"-", ":"} and c for c in cells):
                continue
            if not in_table:
                out.append("<table>")
                in_table = True
            tag = "th" if len(out) == 1 else "td"
            row = "".join(f"<{tag}>{_inline(c)}</{tag}>" for c in cells)
            out.append(f"<tr>{row}</tr>")
            continue
        if in_table:
            out.append("</table>")
            in_table = False
        if stripped.startswith("### "):
            out.append(f"<h3>{_inline(stripped[4:])}</h3>")
        elif stripped.startswith("- "):
            out.append(f"<p class='note'>{_inline(stripped[2:])}</p>")
        elif stripped:
            out.append(f"<p>{_inline(stripped)}</p>")
    if in_table:
        out.append("</table>")
    return "\n".join(out)


def _inline(text: str) -> str:
    """Escape, then apply backtick and bold spans. Pure. `O(n)`.

    Escaping first, so a arm name or a reason string cannot inject markup into
    the card.
    """
    escaped = html.escape(text, quote=False)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    return re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)


def _interval_caveat(table: str) -> list[str]:
    """A warning when the table's interval predates ADR-049. Pure. `O(n)`.

    Read off the table's own bar label rather than the manifest, because the
    manifest does not record which estimator rendered it and the label does —
    the legend travelling with the artifact (ADR-019) doing a second job. Gate
    4b's sweep was rendered before `cluster_bootstrap_points` existed, so its
    intervals are the repeat IQR and are known to understate.
    """
    if LIVE_BAR_LABEL not in table:
        return []
    return [
        "",
        "> **These intervals understate the uncertainty.** They are the "
        "interquartile range over live repeats, which measures run-to-run "
        "variation only. At n=12 the dominant term is *which clips were "
        "drawn*, and this estimator does not carry it — which is why several "
        "are zero-width, reading as precision that is not there. ADR-049 "
        "replaced it with a cluster bootstrap over clips for exactly this "
        "reason. **Re-rendering this table under it is not possible from the "
        "committed artifacts** — a bootstrap resamples clips and only per-arm "
        "aggregates were persisted, so it needs the sweep re-run (ADR-052). "
        "Later runs write `observations.live.json` and are re-analysable.",
    ]


def main(argv: Sequence[str] | None = None) -> int:
    """Run the report CLI.

    Reads the artifacts a sweep left in `--runs` and writes the report card, plus
    `docs/RESULTS.md` and the README's machine-owned region when `--publish` is
    given. `--publish` is opt-in because INV-9's region is only ever written from
    a **live** run, and a simulated table landing in the README would be a
    published number from the wrong upstream (ADR-016).

    Args:
        argv: Arguments, defaulting to `sys.argv[1:]`.

    Returns:
        Process exit code.
    """
    import argparse

    parser = argparse.ArgumentParser(prog="python -m nod_bench.report")
    parser.add_argument("--runs", type=Path, default=Path("bench/runs"))
    parser.add_argument("--out", type=Path, default=Path("bench/report.html"))
    parser.add_argument("--results", type=Path, default=Path("docs/RESULTS.md"))
    parser.add_argument("--readme", type=Path, default=Path("README.md"))
    parser.add_argument(
        "--publish",
        action="store_true",
        help="write docs/RESULTS.md and the README region (live artifacts only)",
    )
    args = parser.parse_args(argv)
    out = sys.stdout

    live = args.runs / artifact_name("results", simulated=False, suffix="md")
    simulated = args.runs / artifact_name("results", simulated=True, suffix="md")
    source = live if live.exists() else simulated
    if not source.exists():
        out.write(
            f"no results table in {args.runs}. Run `make bench` for the "
            f"simulated one, or `make bench-live` for the publishable one.\n"
        )
        return 2
    table = source.read_text(encoding="utf-8")

    if not args.publish:
        out.write(f"read {source}\n(pass --publish to write RESULTS.md and README)\n")
        return 0
    if source is not live:
        out.write(
            f"refusing to publish {source.name}: INV-9 routes every published "
            f"figure through a live run, and this table came from the simulator "
            f"(ADR-016). Run `make bench-live` first.\n"
        )
        return 2

    # Generated onto the table, not written above it: a table leaves this
    # repository as a screenshot far more often than as a file, and a
    # screenshot carries none of the prose around it.
    manifest_path = args.runs / artifact_name(
        "manifest", simulated=False, suffix="json"
    )
    published = table.strip()
    if manifest_path.exists():
        manifest = RunManifest.model_validate_json(manifest_path.read_text())
        published += "\n" + "\n".join(_provenance_footer(None, manifest))
    published += "\n" + "\n".join(_interval_caveat(table))

    # The exact text that went into the README, kept as an artifact. INV-9's
    # provenance check compares the region against *this*, not against the bare
    # table: the footer is generated here, so the raw table is no longer what
    # was published and comparing to it would fail a correct publish.
    composed = args.runs / artifact_name("published", simulated=False, suffix="md")
    composed.write_text(published.strip() + "\n", encoding="utf-8")

    args.results.parent.mkdir(parents=True, exist_ok=True)
    args.results.write_text(RESULTS_HEADER + published.strip() + "\n", encoding="utf-8")
    update_readme_table(args.readme, published)
    out.write(f"wrote {args.results} and the {args.readme} table region\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
